#!/bin/sh
#
# toppl pre-commit hook for quality-checking the commit.
#
# This hook does the following:
#
#   * Checks for trailing whitespace.
#   * Compiles toppl.
#   * Runs the test suite.
#
# Use this hook by symlinking it to your local .git/hooks/ directory.

fail() {
    echo "Aborting commit due to verification errors."
    echo "If you disagree, use git commit --no-verify."
    exit 1
}

echo Quality-checking commit...
echo

# Find files with trailing whitespace
if git diff-index --cached --check HEAD | egrep -v '^[+-]'; then
    fail
fi

if ! stack build; then
    fail
fi

if ! stack exec toppl test tests; then
    fail
fi
