name:                toppl
version:             0.1.0.0
github:              "nqpz/toppl"
license:             GPL-3
author:              "Niels G. W. Serup"
maintainer:          "ngws@metanohi.name"
copyright:           "Copyright (c) 2019 Niels G. W. Serup"

extra-source-files:
- README.md

synopsis:            An aggressive Prolog compiler
category:            Compiler

description:         Please see the README on GitHub at <https://github.com/nqpz/toppl#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5
- mtl
- transformers
- array
- text >= 1.0.0.0
- megaparsec >= 7.00
- prettyprinter >= 1.2
- process >= 1.2.0.0
- language-c-quote >= 0.12
- mainland-pretty >= 0.7
- file-embed >= 0.0.9
- directory >= 1.2.5.0
- filepath >= 1.4.0.0

library:
  source-dirs: src

executables:
  toppl:
    main:                toppl.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - toppl
